### ISSUE TITLE
Breaks when the WooThemes Helper is active

### ISSUE THREAD

**Issue by WPprodigy** [woothemes/homepage-control#21]
Not sure which is at fault here, but you can no longer re-arrange sections once the helper is activated.

![](http://cld.wthms.co/1lbvP/3FUxyXhc+)

@jameskoster

**Comment by jameskoster** [comment]
@WPprodigy do you have Storefront mega menus active by any chance? I saw this exact same issue the other day and reactivating that plugin resolved it.

cc @tiagonoronha

**Comment by WPprodigy** [comment]
Nope, just WC, SF, Hompage Control, and the Helper.

**Comment by rspublishing** [comment]
Seeing same here: https://woothemes.zendesk.com/agent/tickets/394475

**Comment by jameskoster** [comment]
@mattyza you updated the helper recently, are you aware of any changes that might have caused this?

**Comment by mattyza** [comment]
Spotted and resolved. :)

**Comment by mattyza** [comment]
Leaving this issue open, as the fix will be deployed along with the next WooThemes Helper update (no date yet set).

The issue was that the `post` JavaScript was being loaded (for use on the Helper subscriptions screen) with no conditional. This was impacting the Customizer, because the script assumes that `pagenow` is a defined JavaScript variable (which it isn't, within the Customizer).

The fix is in the admin class, if you want to manually apply the fix to any installations.

cc @jameskoster @rspublishing @WPprodigy

**Comment by jeffikus** [comment]
Nice one @mattyza - for those that are interested, https://github.com/woothemes/woothemes-updater/commit/f135479fbf06bee7e21448db4746f96cdaeff75b
